name: E2E Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - 'provider/**'
      - 'patient-portal/**'
      - 'admin-console/**'
      - 'tests/e2e/**'
      - 'package.json'
      - 'assets/webqx-emr-theme.css'
  pull_request:
    branches: [ main ]
    paths:
      - 'index.html'
      - 'provider/**'
      - 'patient-portal/**'
      - 'admin-console/**'
      - 'tests/e2e/**'
      - 'package.json'
      - 'assets/webqx-emr-theme.css'

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Static Server
        run: npx http-server -p 4173 . &
      - name: Wait for server
        run: npx wait-on http://127.0.0.1:4173/index.html
      - name: Run E2E Tests
        env:
          BASE_URL: http://127.0.0.1:4173
        run: npx playwright test --reporter=line
      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report